# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 695fcb65236a15db62bab680ebcdbbae5deb10b5d1b41a9673e4181225beecdcc08fb87cf9f6238a2d7b74862f861843d64b4084b2313f2ab985b1d944e2fa51

test:
  secret_key_base: 4242d063a0b403a293b859204f654e73c9394502410929f02b4646a698e82e200b41c260f21c68be732605ae961905f025fc75fe1b36826ca2be01202131bfe9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
